name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: latexmk
          latexmk_use_xelatex: true
      - name: Rename PDF file
        run: |
          mv resume.pdf BransonCV.pdf
      - name: Commit PDF to repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add BransonCV.pdf
          git commit -m "Update compiled CV" || echo "No changes to commit"
          git push
