name: Build LaTeX document
on: [push]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: xelatex
          args: -interaction=nonstopmode  # Continue even if there are errors
        continue-on-error: true  # Continue even if LaTeX returns an error code
      - name: Rename PDF
        run: |
          if [ -f "resume.pdf" ]; then
            mv resume.pdf BransonCV.pdf
            echo "PDF successfully renamed"
          else
            echo "resume.pdf not found!"
            ls -la
            exit 1
          fi
      - name: Commit PDF to repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add BransonCV.pdf
          git commit -m "Update compiled CV" || echo "No changes to commit"
          git push
